### ISSUE TITLE
honor settings in `.editorconfig` and `.eslintrc`

### ISSUE THREAD

**Issue by c-vetter** [RobinMalfait/prettier-eslint-code#15]
Hey there,
First of all: Thank you for the extension 😄 

Now, I do have one issue at this point: in my project, I have an `.editorconfig` and an `.eslintrc`. Both say to indent with 4 spaces, but `prettier.tabWidth` is set to 2. Curiously, for most lines, this works out to 4 spaces indentation, but comment lines are indented with 2 spaces. It would be great for `prettier` to use the setting from `.editorconfig`, possibly falling back to `.eslintrc`, before using `prettier.tabWidth`.

**Comment by RobinMalfait** [comment]
It's a good idea but I think that it is outside of the scope of this project.

1. I might shut this plugin down because all the functionality is in https://github.com/esbenp/prettier-vscode now
2. I don't think that having 20 config files to do the same thing is a good solution?

Also it will first do prettier and then run eslint --fix, thus the tabWidth should be set to 4. Could it be that the tabWidth changes to 2 once you open op the file in your editor AND another rule in .editorconfig is overlapping?

**Comment by c-vetter** [comment]
Ok, I see 🤔 `prettier-vscode` actually solved this problem, and eslint is going to as well in 4.0. So, thank you for the tip. And I think you are correct: if `prettier-eslint-code` is functionally a subset of `prettier-vscode`, everyone would benefit from your joining that project and deprecating this one 👍 

As for having 20 config files: I don't advocate that either, but the fact of the matter is that `.eslintrc` files and `.editorconfig` files are per-project, while VSCode settings are not, and therefore the former should take precedence over the latter.
