### ISSUE TITLE
prettier-eslint-code setup explanation for a 5 year old :D

### ISSUE THREAD

**Issue by GollyJer** [RobinMalfait/prettier-eslint-code#5]
Hi!
I'm currently using the prettier supported vscode extension and it works great to auto-format the code, but I'm looking to get eslint hinting and rules in vscode along with prettier.  

This extension seems like the way to make that happen.

Can someone walk me through setting things up from beginning to end? 
Assume a brand new empty project. Do the steps look something like this?

- Turn off vscode default code formatting somehow???
- Install prettier-eslint-code extension in vscode.
- **yarn add prettier-eslint**  in the project
- do something to set up eslint rules???
- start coding

Thanks!

**Comment by RobinMalfait** [comment]
Hello!

The plugin itself is bundled with the prettier-eslint dependencies, so basically if you have a new project you have to install `eslint` (unless you already have it globally installed) and you have to provide an `.eslintrc` file (Those can be json, yaml, ... files look at the eslint docs).

To answer some of you questions:

- Turn off vscode default code formatting somehow???
  - Nope, the vscode plugin registers itself as a 'formatter', which means if you use the format command it will just work as expected.
  - If you want to auto-format it, you can enable a setting in vscode 
```js
  // Format a file on save. A formatter must be available, the file must not be auto-saved, and editor must not be shutting down.
  "editor.formatOnSave": false,
```

- Install prettier-eslint-code extension in vscode.
  - You only have to do this once, because extensions in vscode are global. (You can disable extensions for certain projects if you want though)

- yarn add prettier-eslint in the project
  - This is not needed because the plugin has it already bundled. If you don't have eslint installed you might need to install that `yarn add eslint --dev`. Don't forget the `--dev` flag, because you don't want that to end up in your production build.
- do something to set up eslint rules???
  - If you have a `eslintrc` file, it will use that format your code.
- Start coding
  - yes!

To see warnings in vscode from eslint, you can use: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

I hope these answered your questions, if not, feel free to contact me ;)

**Comment by GollyJer** [comment]
Let's say I want to set 
`"prettier.printWidth": 100`
Where do I do that in the _prettier-eslint-code_ world?

**Comment by RobinMalfait** [comment]
That is a good question, currently it is not possible. But if you can wait ~2hours it will be available for you.

**Comment by RobinMalfait** [comment]
If you update your plugin in vscode, you will be able to set `"prettier.printWidth": 100`!
